# Database Configuration (XAMPP MySQL)
# spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:postgresql://dpg-d6okkvvkijhs73cd9dkg-a
spring.datasource.username=hospital_db_0g5f_user
spring.datasource.password=5FqrjlFx2yzIw46Gbivd3T73QbhRxiwk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT Configuration
app.jwt.secret=HospitalSystemSecretKey2024VeryLongAndSecureKeyForJWTTokenGeneration
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.hospital=DEBUG




# ===============================
# XAMPP MySQL Configuration
# ===============================


# for local MySQL setup (XAMPP):

# spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # ===============================
# # Hibernate
# # ===============================
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # ===============================
# # Server
# # ===============================
# server.port=8081

# # JWT Configuration
# app.jwt.secret=HospitalSystemSecretKey2024VeryLongAndSecureKeyForJWTTokenGeneration
# app.jwt.expiration=86400000

# # ===============================
# # CORS Configuration
# # ===============================
# app.cors.allowed-origins=http://localhost:3000